name: Main CI-pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkstyle
        run: make check_fmt
 
      - name: quad_eq_Test
        run: make quad_eq_test

      - name: stack_test
        run: make stack_test
      